export default function Head() {
  return (
    <>
      <title>Menu of Milestones Grill (Toronto) | OpenTable</title>
      <meta content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by Create next app" />
    </>
  );
}
