export default function Head() {
    return (
      <>
        <title>Search Restaurants OpenTables</title>
        <meta content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by Create next app" />
      </>
    );
  }
  